const mongoose = require('mongoose');
const User = require('../models/user');
const Nonprofit = require('../models/nonprofit');
const Skill = require('../models/skill');


const { dbURI } = require('../config/environment');
mongoose.Promise = require('bluebird');

mongoose.connect(dbURI, { useMongoClient: true });

User.collection.remove();
Nonprofit.collection.remove();
Skill.collection.remove();

Skill.create([
  { name: 'Accounting' },
  { name: 'Administrative / Secretarial' },
  { name: 'Advertising' },
  { name: 'Aircraft Mechanic' },
  { name: 'Android Developer' },
  { name: 'Architect' },
  { name: 'Art Curator' },
  { name: 'Auction House' },
  { name: 'Automotive' },
  { name: 'Banking' },
  { name: 'Barista' },
  { name: 'Bartender' },
  { name: 'Beautician' },
  { name: 'Big Data' },
  { name: 'Biomedical Engineer' },
  { name: 'Blue Collar Jobs' },
  { name: 'Boilermaker' },
  { name: 'Bookkeeping' },
  { name: 'Brick Mason' },
  { name: 'Broadcaster' },
  { name: 'Business Analyst' },
  { name: 'Business Development' },
  { name: 'Business Intelligence' },
  { name: 'Business Manager' },
  { name: 'Career Counselor' },
  { name: 'Carpentry' },
  { name: 'Cashier' },
  { name: 'Chef' },
  { name: 'Chiropractor' },
  { name: 'Civil Engineer' },
  { name: 'Claims Adjuster' },
  { name: 'Clinical Laboratory Technician' },
  { name: 'Cloud Computing' },
  { name: 'College Admissions' },
  { name: 'Computer' },
  { name: 'Computer Programming' },
  { name: 'Computer Systems Analyst' },
  { name: 'Concierge' },
  { name: 'Construction' },
  { name: 'Content Manager' },
  { name: 'Content Strategist' },
  { name: 'Counseling' },
  { name: 'Consulting' },
  { name: 'Custodian' },
  { name: 'Customer Service' },
  { name: 'Database Administrator' },
  { name: 'Data Analyst' },
  { name: 'Data Scientist' },
  { name: 'Dental Assistant' },
  { name: 'Dental Hygienist' },
  { name: 'Dentist' },
  { name: 'Dietician / Nutritionist' },
  { name: 'Digital Media' },
  { name: 'Editing' },
  { name: 'Electrician' },
  { name: 'EMT / Firefighter' },
  { name: 'Esthetician' },
  { name: 'Executive' },
  { name: 'Executive Assistant' },
  { name: 'Engineering' },
  { name: 'Fashion Design' },
  { name: 'Fashion Buyer' },
  { name: 'Fast Food' },
  { name: 'Finance' },
  { name: 'Financial Advisor / Planner' },
  { name: 'Flight Attendant' },
  { name: 'Front End Web Developer' },
  { name: 'Fundraiser' },
  { name: 'Graphic Design' },
  { name: 'Hair Stylist' },
  { name: 'Health Care Skills Listed by Job' },
  { name: 'Health / Medical Information Technician' },
  { name: 'Healthcare / Hospital Administration' },
  { name: 'Heavy Equipment Operator' },
  { name: 'Home Health Aide' },
  { name: 'Hospitality Industry' },
  { name: 'Hotel Front Desk / Guest Services Skills' },
  { name: 'Hotel and Resort Management' },
  { name: 'Human Resources' },
  { name: 'Information Security Analyst' },
  { name: 'Inside Sales' },
  { name: 'Insurance' },
  { name: 'Interior Design' },
  { name: 'Information Technology' },
  { name: 'Investment Banking Analyst' },
  { name: 'iOS Developer' },
  { name: 'IT Manager' },
  { name: 'IT Soft Skills' },
  { name: 'Journalist' },
  { name: 'Gardening, Landscaping, and Groundskeeping' },
  { name: 'Law Enforcement Skills' },
  { name: 'Legal' },
  { name: 'Librarian' },
  { name: 'Licensed Practical Nurse (LPN) Skills' },
  { name: 'Machinist' },
  { name: 'Maintenance and Janitorial' },
  { name: 'Makeup Artist' },
  { name: 'Management' },
  { name: 'Management Trainee' },
  { name: 'Marketing Automation Specialist / Manager' },
  { name: 'Market Research Analyst' },
  { name: 'Marketing' },
  { name: 'Massage Therapist' },
  { name: 'Mechanical Engineer' },
  { name: 'Medical Assistant' },
  { name: 'Media Planner / Buyer' },
  { name: 'Medical Secretary' },
  { name: 'Meteorologist' },
  { name: 'Museum Curator' },
  { name: 'Naturopathic Physician' },
  { name: 'Nurse Practitioner' },
  { name: 'Nursing' },
  { name: 'Nursing Assistant' },
  { name: 'Occupational Therapist' },
  { name: 'Occupational Therapy Assistant' },
  { name: 'Office Assistant' },
  { name: 'Office Manager' },
  { name: 'Optician' },
  { name: 'Painter' },
  { name: 'Paralegal / Legal Assistant' },
  { name: 'Personal Assistant' },
  { name: 'Personal Trainer' },
  { name: 'Pharmaceutical Sales' },
  { name: 'Pharmacist' },
  { name: 'Pharmacy Technician' },
  { name: 'Phlebotomist' },
  { name: 'Photography' },
  { name: 'Physical Therapy Assistant' },
  { name: 'Physical Therapist' },
  { name: 'Physician' },
  { name: 'Physician Assistant' },
  { name: 'Pilot' },
  { name: 'Pipefitter' },
  { name: 'Plumber' },
  { name: 'Policy Analyst' },
  { name: 'Product Manager' },
  { name: 'Project Manager' },
  { name: 'Public Health' },
  { name: 'Public / Non Profit Administrator' },
  { name: 'Public Relations' },
  { name: 'Radiologic Technologist' },
  { name: 'Real Estate' },
  { name: 'Receptionist' },
  { name: 'Research Assistant' },
  { name: 'Respiratory Therapist' },
  { name: 'Retail' },
  { name: 'Retail Associate' },
  { name: 'Retail Buyer' },
  { name: 'Retail Manager' },
  { name: 'Retail Merchandiser' },
  { name: 'Retail Sales' },
  { name: 'Restaurant and Food Service' },
  { name: 'Restaurant Host / Hostess' },
  { name: 'Sales' },
  { name: 'Sales Associate' },
  { name: 'Search Engine Optimization (SEO)' },
  { name: 'School Psychologist' },
  { name: 'Scrum Master' },
  { name: 'Server' },
  { name: 'Social Media' },
  { name: 'Social Work' },
  { name: 'Software Developer' },
  { name: 'Software Engineer' },
  { name: 'Software Quality Assurance (QA) Engineer' },
  { name: 'Software Sales Representative' },
  { name: 'Speech Pathologist' },
  { name: 'Surveyor' },
  { name: 'Teaching' },
  { name: 'Tech Skills Listed by Job' },
  { name: 'Tech Support' },
  { name: 'Technical Support Engineer' },
  { name: 'Technical Writer' },
  { name: 'Telecommunications Equipment Installer' },
  { name: 'Television / Film Producer' },
  { name: 'Training Coordinator' },
  { name: 'Travel Agent / Coordinator' },
  { name: 'Truck Driver' },
  { name: 'Ultrasound Technician' },
  { name: 'Underwriter' },
  { name: 'User Experience / User Interface' },
  { name: 'Veterinary Technician' },
  { name: 'Waiter / Waitress' },
  { name: 'Web Design' },
  { name: 'Wedding / Special Events Planner' },
  { name: 'Welder' },
  { name: 'Writing' }
])
  .then(skills => {
    console.log(`${skills.length} skilz created!`);
    return User.create([
      {
        username: 'Person',
        firstName: 'Person',
        lastName: 'Person',
        email: 'person@person.com',
        image: '...',
        description: 'do gooder',
        address: 'road street',
        password: 'password',
        passwordConfirmation: 'password',
        skills: [skills[0], skills[2], skills[5]]
      }
    ]);
  })
  .then(users => {
    console.log(`${users.length} users created!`);
  })
  .catch(err => console.log(err))
  .finally(() => mongoose.connection.close());
